### PR TITLE
fix: Replace packpath with pkginfo to get metadata in more reliable f…

### PR DESCRIPTION
**Pull request by TomRK1089**
…ashion

Further testing revealed packpath did not work consistently in Jest tests.

### CODE REVIEW

**Comment by TomRK1089** [comment]
I was not able to get `packpath` to behave for the Jest tests. Ultimately decided to use a slightly different dependency to retrieve package metadata. It's slightly clunkier requiring an extra file to attach the metadata to but the tests that Travis showed as failed before pass for me now. Sorry for the confusion!

**Comment by TomRK1089** [comment]
@mefellows Again, sorry for the premature merge/tag. Thankfully Travis is smarter than I am. :)

**Comment by mefellows** [comment]
Thanks @TomRK1089 - no problems. This is a WIP branch so happy to bring things in quicker. I'd be more cautious in master :)

**Comment by mefellows** [comment]
FYI `v6.0.0-alpha.10` is now live with these changes 🙏

**Pull request merged**
