### PR TITLE
docs(verify): better describe the verify method

### PR DESCRIPTION
**Pull request by lirantal**
In response to our discussion on gitter with @mefellows and @bethesque about how the verify method works.

### CODE REVIEW

**Comment by mefellows** [comment]
thanks!

**Comment by bethesque** [comment]
I'd prefer not to mention the query parameters! That's probably a bug. Also, this wording very unspecific. If you specify parameters, and they don't match, the request will not match, and that is not clear from this wording.

**Comment by bethesque** [comment]
I've found some documentation on request matching that I'd forgotten about. I've included a link to it in that section.

**Comment by lirantal** [comment]
@bethesque I'm more than happy to correct. What's the link to the documentation you found? and also let's wait to see if this is a bug or what :)

**Comment by bethesque** [comment]
I've updated that section, you'll see the link there now.

**Comment by lirantal** [comment]
super! looks good.

**Pull request merged**
