### PR TITLE
test: check encoded query parameters

### PR DESCRIPTION
**Pull request by individual-it**
### PR Template
Tests for #589 
This is specially to check the correct encoding in the query parameters

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks for this @individual-it. I haven't been through the context of this, but will. 

@TimothyJones want me to take a look at this? I know you've done some work on the examples recently.

**Comment by individual-it** [comment]
the new tests now pass also on appveyor but CI fails in the publish state, I'm currently looking at it

**Comment by individual-it** [comment]
the issue with the appveyor CI is that there is no brocker running

**Comment by mefellows** [comment]
Hmmm, the e2e test usually points to test.pactflow.io. I'll have to check the code to see if the new build runs a local broker (we've talked about it, but to my knowledge no action has been taken on it yet).

**Comment by mefellows** [comment]
The build is failing because it's trying to talk to a local broker (see https://github.com/pact-foundation/pact-js/commit/4f1b87a4d1771974208ae05f3581db30d831ba01), but no broker has been started.

So that's an issue for us to fix (point to remote account or update the appveyor script to start the container).

**Comment by individual-it** [comment]
CI hopefully get fixed by #613

**Comment by TimothyJones** [comment]
@mefellows If you could take a look, that would be awesome!

Some of the issues can be fixed by merging master in- it looks like that hasn't happened for a while.

**Comment by individual-it** [comment]
looks like #613 fixes CI, so merging and rebasing on it should fix it here too

**Comment by individual-it** [comment]
CI is green after rebasing on top of #613

**Comment by TimothyJones** [comment]
Oops, thought we had merged this already. I'll do it now.

Thanks again!

**Pull request merged**
