### PR TITLE
fix: Add Date as a valid JSON value

### PR DESCRIPTION
**Pull request by jwmcconnell**
- [x] `npm run dist` works locally (this will run tests, lint and build)
- [x] Commit messages are ready to go in the changelog (see below for details)
- [x] PR template filled in (see below for details)

## PR Template

Add Date as a valid JSON value.

### CODE REVIEW

**Comment by mefellows** [comment]
Unless I'm mistaken, Date is not a valid JSON value type. Can you please elaborate on what you're trying to achieve here?

**Comment by TimothyJones** [comment]
I agree with Matt.

**Comment by jwmcconnell** [comment]
> Unless I'm mistaken, Date is not a valid JSON value type. Can you please elaborate on what you're trying to achieve here?

Sorry for the confusion, I was attempting to transform an example of yours to use one of my types and made a mistake with the consumer test.

**Comment by mefellows** [comment]
No probs!

**Pull request closed without merging**
