### PR TITLE
feat(pact-server): pact server supports config from env

### PR DESCRIPTION
**Pull request by lirantal**
Supports providing Pact Server configuration through environment variables

### CODE REVIEW

**Comment by mefellows** [comment]
It's a good idea and looks OK to me, I'll have a broader look later today - perhaps we can make this extend into other parts of the configuration.

**Comment by lirantal** [comment]
Cool.

**Comment by bethesque** [comment]
This assumes you're only using one mock server.
It would be more accurate to call it PACT_MOCK_SERVICE_HOST and PACT_MOCK_SERVICE_PORT because the PACT_SERVER is ambiguous. Is it the mock server, the server you're verifying, or the server you're retrieving the pacts from?

**Comment by lirantal** [comment]
Agree on the naming convention.

With regards to the mock server, I think the env params can be used as defaults for when the mock server provider is bootstrapped such as:
```
pact({
  consumer: '',
  provider: '',
  host: '',
  port: ''
})
```

**Comment by mefellows** [comment]
Hi @lirantal, I'm going to close this as it is embarrassingly overdue (from our end). I'll raise a separate issue to capture the intention of this where we can discuss the value in doing an ENV based config.

**Pull request closed without merging**
