### PR TITLE
feat: allow also WebDAV HTTP Requests

### LINKED ISSUE #494: supported WebDAV HTTP methods
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request

WebDAV methods like `MKCOL` (https://en.wikipedia.org/wiki/WebDAV#Implementation) are not supported, trying to use them results in an error `Failed: You must provide a valid HTTP method: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS.`

### PR DESCRIPTION
**Pull request by individual-it**
fixes #494

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks again @individual-it - loving your contribution to our community! 🌮

**Comment by individual-it** [comment]
travis fails with 
image

is that because the PR comes from a fork?

**Comment by mefellows** [comment]
Just an FYI, this PR will depend on an upgrade to the latest Ruby standalone binary that adds support for arbitrary verbs. I'll leave it open and merge them together so I can check.

**Comment by mefellows** [comment]
Thanks @individual-it - i'll pull this in and make sure it works!

**Pull request merged**
