### PR TITLE
chore(deps): update to support nestjs 8

### PR DESCRIPTION
**Pull request by omermorad**
Thank you for making a pull request!

Pact-JS is built and maintained by developers like you, and we appreciate contributions very much. You are awesome!

Here is a short checklist to give your PR the best start:

_Everything above can be removed once checked_

- [x] `npm run dist` works locally (this will run tests, lint and build)
- [x] Commit messages are ready to go in the changelog (see below for details)
- [x] PR template filled in (see below for details)

# Commit messages

Our changelog is automatically built from our commit history, using conventional changelog. This means we'd like to take care that:

- commit messages with the prefix `fix:` or `fix(foo):` are suitable to be added to the changelog under "Fixes and improvements"
- commit messages with the prefix `feat:` or `feat(foo):` are suitable to be added to the changelog under "New features"

If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do a squash
merge, but you'll lose attribution for your change.

For more information please see CONTRIBUTING.md

_Everything above can be removed_

### PR Template

Updating NestJS examples to new `nestjs-pact`

### CODE REVIEW

**Comment by omermorad** [comment]
@TimothyJones
`PactBroker::Client::Error - Command `git rev-parse --abbrev-ref HEAD` didn't return anything that could be identified as the current branch.`

Can you help?

**Comment by TimothyJones** [comment]
That's a problem that happens on PR builds at the moment, you can safely ignore it (the windows build works fine).

There are a lot of warnings printed from those examples - one about typescript misconfiguration, some vulnerability complaints, and also this warning:

https://github.com/pact-foundation/pact-js/runs/4828513197?check_suite_focus=true#step:4:1565 

which is caused by https://github.com/omermorad/nestjs-pact/issues/7

Do you think we could fix those while we're looking at nestjs-pact?

**Comment by omermorad** [comment]
> That's a problem that happens on PR builds at the moment, you can safely ignore it (the windows build works fine).
I'm going to create a PR to fix it

> There are a lot of warnings printed from those examples - one about typescript misconfiguration, some vulnerability complaints, and also this warning:
Will fix those in another PR(?)

> which is caused by [omermorad/nestjs-pact#7](https://github.com/omermorad/nestjs-pact/issues/7)
> Do you think we could fix those while we're looking at nestjs-pact?

Explain please

**Comment by TimothyJones** [comment]
For the PR build issue, I don't think it can be fixed in this repo (although if you know a fix, I would welcome it!). I think this is the cause: https://github.com/pact-foundation/pact_broker-client/issues/102

For this issue, omermorad/nestjs-pact#7 , there's this line here: https://github.com/omermorad/nestjs-pact/blob/master/src/services/pact-verifier.service.ts#L19 , where we have

```
 this.verifier.verifyProvider({
      ...this.options,
      providerBaseUrl: appUrl,
 });
```

This produces [this warning during the build](https://github.com/pact-foundation/pact-js/runs/4856632698?check_suite_focus=true#step:4:1489):

```
pact@9.17.2: Passing options to verifyProvider() wil be deprecated in future versions, please provide to Verifier constructor instead
```
 
This needs to be changed so that the options are passed in when the verifier object is constructed: 
 
```
new Verifier({  
    ...this.options,
    providerBaseUrl: appUrl,
});
```

**Comment by YOU54F** [comment]
Hey @omermorad, the build errors should be all resolved now, is there any chance you could get some time to look at https://github.com/omermorad/nestjs-pact/issues/7

If you don't have the time, let me know and I can look at getting it updated, pulled in, and this PR merged. wdyt?

**Comment by omermorad** [comment]
> Hey @omermorad, the build errors should be all resolved now, is there any chance you could get some time to look at [omermorad/nestjs-pact#7](https://github.com/omermorad/nestjs-pact/issues/7)
> 
> If you don't have the time, let me know and I can look at getting it updated, pulled in, and this PR merged. wdyt?

Hi @YOU54F!
There is an open pull request regarding this one: https://github.com/omermorad/nestjs-pact/pull/13
I'm going to copy the NestJS examples from this repo into the nestjs-pact repo in order to test this PR

CC: @bewatts

**Comment by YOU54F** [comment]
Thanks for that buddy, whilst you are tickling the example code, is it worth looking at this issue

https://github.com/pact-foundation/pact-js/issues/863#issue-1215749870

maybe aligning the provider and consumer ports so the user can see the app running e2e would be useful, not sure if we do that across the other examples,

And adding a covering readme for the example? It could even just be a link to your readme for nestjs-pact as it looks pretty good and saves duplication.

Thoughts welcome

**Comment by YOU54F** [comment]
Also just looking at the package.json nest-js is still at a v7.x rel. should this bump it to 8 aswell?

**Comment by mefellows** [comment]
Is this PR defunct now?

**Comment by mefellows** [comment]
Closing due to stale.

**Pull request closed without merging**
