### PR TITLE
add TypeScript annotations

### PR DESCRIPTION
**Pull request by Narazaka**

### CODE REVIEW

**Comment by mefellows** [comment]
This is great, thanks @Narazaka! I'll review this tomorrow, but in the meanwhile one thing that I'm worried about is the code drifting from the annotations. Is there any checks or tests that we can put in place to prevent the drift?

**Comment by Narazaka** [comment]
hmm... I regret to say that I do not have the idea of stopping the gap between annotation and code. That's why I made a pull request to pact-js instead of DefinitelyTyped, expecting higher maintenance possibilities.

**Comment by mefellows** [comment]
Hi @Narazaka, I've chatted to a few people and I'm going to bring this in. Thanks for this, I've verified that VS code picks this up immediately locally - it's great!

To ensure you get the credit for this PR, can I please ask that you squash all of your commits with the message `feat(typescript): add TypeScript annotations`

I need to update `CONTRIBUTING.md` - we follow the committizen conventions.

**Comment by mefellows** [comment]
(don't worry about the red build, there is a flakey Karma test in there we need to fix)

**Comment by Narazaka** [comment]
Thank you for taking in!

**Comment by mefellows** [comment]
Released `v2.3.3` :shipit:

**Pull request merged**
