### PR TITLE
feat(example): adding example for the AVA test framework

### PR DESCRIPTION
**Pull request by lirantal**
* Adds a small example project that makes use of the popular AVA test framework
* Updates README with a link to it alongside Jest and Mocha.

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks!

**Comment by abruzzi** [comment]
Is there any example of the `Pact.Matchers` APIs? like `like, term, eachLike` , thanks.

**Comment by lirantal** [comment]
I'll take a look at it. Also need to update how it works.

**Comment by lirantal** [comment]
@abruzzi there you go: https://github.com/pact-foundation/pact-js/pull/133
you're also welcome to contribute to the examples and extend them :-)

**Pull request merged**
