### PR TITLE
add logging of test failed reason when testFn throws exception

### LINKED ISSUE #909: [V3] Pact.log is gone?
_Thank you for making a feature request! We appreciate it very much. GitHub Issues are a big input into the priorities for Pact-JS development_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

### Checklist

_This checklist is optional, but studies show that people who have followed it checklist are really excellent people and we like them_

Before making a feature request, I have: 

- [x] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js/issues?q=is%3Aissue)
- [x] Checked the documentation to see if it is possible to do what I want already 

### Feature description

To be able to see logs in pact.log again. It seems that pact.log is completely gone with V3.

### Use case

So that it's possible to diagnose a mismatch issue without putting lots of console logs in my codebase and staring at errors like that:
```
data: {
        error: 'Request-Mismatch : HttpRequest { method: "POST", path: "/account/exist", query: None, headers: Some({"connection": ["close"], "accept": ["application/json", "text/plain", "*/*"], "x-app-version": ["1.0.0"], "x-app-platform": ["ios"], "user-agent": ["axios/0.27.2"], "content-length": ["24"], "host": ["127.0.0.1:56111"], "x-app-timezone": ["Europe/Paris"], "content-type": ["application/json; charset=utf-8"]}), body: Present(b"{\\"username\\":\\"username1\\"}", Some(ContentType { main_type: "application", sub_type: "json", attributes: {"charset": "utf-8"}, suffix: None }), None), matching_rules: MatchingRules { rules: {} }, generators: Generators { categories: {} } }'
      }
    }
```
I still have no clue what is it trying to tell me. 

To add a bit more contex. Apparently, this particular issue happens if my own code throws an error on 500. In that scenario I cannot see pact logs which tell me what was the mismatch.

I was able to circumvent it with empty try catch:
```
try {
        await validateUsername({
          username,
          api: new Api(mockServer.url),
        });
      } catch (error) {}
```
And then I get proper errors:
```
Mock server failed with the following mismatches:

        0) The following request was incorrect: 

                POST /account/exist
              
                         1.0 Expected a Map with keys email, username but received one with keys username
```
Wondering if it's expected and should pact catch all exceptions and return them back with mismatches?

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
Adds logging when test threw an exception. Fixes #909

### CODE REVIEW

**Review by Maxim-Filimonov — COMMENTED** [review]
Adds logging when test threw an exception. Fixes #909

**Comment by Maxim-Filimonov** [comment]
Last commit fixes the log.
```
 Test failed for the following reasons:

      Mock server failed with the following mismatches:

        0) The following request was incorrect: 

                POST /account/exist
              
                         1.0 Expected a Map with keys username but received one with keys email, username

     Original exception: 
    Error: There was a problem processing the request
```

**Review by TimothyJones — APPROVED** [review]
Looks good to me. It might be nicer if that `let` could be a `const`, but that's just personal preference.

**Comment by mefellows** [comment]
Apologies @Maxim-Filimonov, I somehow missed this contribution. This was implemented in #922 

Thank you for putting it together though, it is much appreciated!

**Pull request closed without merging**
