### PR TITLE
fix: "consumerVersionSelectors" verification option in readme

### PR DESCRIPTION
**Pull request by neildevas**
Fix typo in readme for the provider verification option "consumerVersionSelectors"

### CODE REVIEW

**Comment by TimothyJones** [comment]
Good eye! I think this change is right - is there a reason it was closed?

**Comment by neildevas** [comment]
> Good eye! I think this change is right - is there a reason it was closed?

Not a good one - got frustrated that it was failing semantic pull request step :/

**Comment by TimothyJones** [comment]
No problem, we can squash merge when the commits don't follow the convention :+1:

**Comment by TimothyJones** [comment]
Thanks very much for the PR!

**Pull request merged**
