### PR TITLE
chore(deps): Typescript example - maintenance - versions, warnings, speedup

### PR DESCRIPTION
**Pull request by andreasmarkussen**
# Minor updates for the TypeScript example:

 * ~~Mocha Maintainance - removed deprecation warning (--compilers)
    https://github.com/mochajs/mocha/wiki/compilers-deprecation~~ moved to PR 340
 * Updated dependencies (bumped versions in package.json)
 * Added a 'run script' that runs Mocha directly - 20% faster but without code-coverage

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks @andreasmarkussen, I'll take a look at this later today. 👍

**Comment by TimothyJones** [comment]
The execution of the example is failing on node 6 and 7 (typescript compile error, by the looks of it).

**Comment by andreasmarkussen** [comment]
> The execution of the example is failing on node 6 and 7 (typescript compile error, by the looks of it).

Hi @TimothyJones, 
OK - I will look into it, could you be a bit more specific into the compilation errors? 
Perhaps you have some docker image id's that you have used? 
Andreas

**Comment by TimothyJones** [comment]
Apologies, I had thought that the build output was public (it should be). Here is the error:

```
9095/home/travis/build/pact-foundation/pact-js/examples/typescript/node_modules/chalk/index.js:72
9096ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
9097                                                                         ^
9098TypeError: Cannot read property 'close' of undefined
9099    at Object.<anonymous> (/home/travis/build/pact-foundation/pact-js/examples/typescript/node_modules/chalk/index.js:72:74)
9100    at Module._compile (module.js:571:32)
9101    at Module.replacementCompile (/home/travis/build/pact-foundation/pact-js/examples/typescript/node_modules/append-transform/index.js:58:13)
9102    at Module._extensions..js (module.js:580:10)
9103    at Object.<anonymous> (/home/travis/build/pact-foundation/pact-js/examples/typescript/node_modules/append-transform/index.js:62:4)
9104    at Module.load (module.js:488:32)
9105    at tryModuleLoad (module.js:447:12)
9106    at Function.Module._load (module.js:439:3)
9107    at Module.require (module.js:498:17)
9108    at require (internal/module.js:20:19)
```

**Comment by mefellows** [comment]
The build is public, can you not get to it?

https://travis-ci.org/pact-foundation/pact-js

**Comment by mefellows** [comment]
Thanks stalebot for the reminder - @andreasmarkussen,  are you still interested in finishing this PR?

**Comment by andreasmarkussen** [comment]
Yes - Just got back from a long vacation! 
Yes - I do want to complete the PR - but I need to refresh my fork and try again? 
The other PR 340 was merged.

**Comment by mefellows** [comment]
Welcome and lucky you!? (I'm also just returning from a short try to Fiji for a wedding :P)

Yes, please feel free to tag me when you're ready.

**Comment by TimothyJones** [comment]
Much appreciated, thanks!

**Pull request merged**
