### PR TITLE
chore: update misspelling in docs example test

### PR DESCRIPTION
**Pull request by BrentGTR**
RE: Really minor change that may help a noob (like me) understand the test better. 

Thank you for making a pull request!

Pact-JS is built and maintained by developers like you, and we appreciate contributions very much. You are awesome!

Here is a short checklist to give your PR the best start:

_Everything above can be removed once checked_

- [ ] `npm run dist` works locally (this will run tests, lint and build)
- [ ] Commit messages are ready to go in the changelog (see below for details)
- [ ] PR template filled in (see below for details)

# Commit messages

Our changelog is automatically built from our commit history, using conventional changelog. This means we'd like to take care that:

- commit messages with the prefix `fix:` or `fix(foo):` are suitable to be added to the changelog under "Fixes and improvements"
- commit messages with the prefix `feat:` or `feat(foo):` are suitable to be added to the changelog under "New features"

If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do a squash
merge, but you'll lose attribution for your change.

For more information please see CONTRIBUTING.md

_Everything above can be removed_

### PR Template

_Please describe what this PR is for, or link the issue that this PR fixes_

_You may add as much or as little context as you like here, whatever you think is right_

_Thanks again!_

### CODE REVIEW

**Comment by mefellows** [comment]
Great spot!

Sorry to be finicky, but could you please reword your commit

e.g.

```
chore: update misspelling in docs example test
```

The reason is we use semantic commits to generate the changelog.

**Comment by mefellows** [comment]
I'm still seeing this, sorry. Did you push your commit?

Screenshot 2024-07-08 at 6 08 57 PM

**Comment by BrentGTR** [comment]
Apologies. I had to create another commit (white space) because the commit name did not reflect.

**Comment by mefellows** [comment]
Ah, you need to do something like this `git commit --amend -m "<your message...>"` to overwrite an existing commit (or use the `rebase` sub-command).

Anyway - thanks for this!

**Pull request merged**
