### PR TITLE
feat: filter verification by description & state

### PR DESCRIPTION
**Pull request by individual-it**
- [x] `npm run dist` works locally (this will run tests, lint and build)
- [x] Commit messages are ready to go in the changelog (see below for details)
- [x] PR template filled in (see below for details)

allow to run verifications for specific interaction description and/or state same as in the current version of Pact JS:  https://github.com/pact-foundation/pact-js#re-run-specific-verification-failures

I confess that I hacked this together without any knowledge of Rust just by staring at the code and googling, so any comment is appreciated
interaction filter if statements taken from https://github.com/pact-foundation/pact-reference/blob/dfd3ba973d22fc092061e8d905d0b4aeba65856b/rust/pact_verifier_ffi/src/verifier.rs#L97-L116 

fixes: #622 

ToDo:
- [x] change docs
- [x] create tests

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks Artur - will take a pass through this tomorrow!

**Comment by mefellows** [comment]
Just noting, I will add these env vars to the Rust code for the verifier.

**Comment by individual-it** [comment]
@mefellows I've adapted the docs and wrote some tests.
How the tests work:
There are some pact files that contain some interactions that would pass and some that would fail if executed. In the test the filter should select only the passing interactions (by setting the env. variable in the spec file via `process.env`. 
So if the test run passes that should prove that the filter works correctly. And if the filter selects the wrong interactions the test run should fail.
Even that is a bit of a weird way to test I choose it (above writing rust unit tests) because as I understood @TimothyJones the rust code would be obsolete soon and that way the tests are implementation agnostic and should prove if the new implementation works correctly or not

**Comment by individual-it** [comment]
Windows tests fail, investigating the reason ...

**Comment by individual-it** [comment]
windows tests pass now after adding a fix in the powershell script that @uglyog already added in the bash script in https://github.com/pact-foundation/pact-js/commit/aac2961e99064b611e1c7d75fe46c5b5f33a3927

**Comment by mefellows** [comment]
Thanks Artur! I'll take a look next week. I'd like to also enable them behind a flag for consistency, so will review it all then.

**Pull request merged**
