### PR TITLE
chore(deps): Move @types/* to devDependencies

### PR DESCRIPTION
**Pull request by vgrigoruk**
@types/* packages should be in devDependencies instead of runtime dependencies.

### CODE REVIEW

**Comment by mefellows** [comment]
I thought the same, but actually these are needed for some typescript configuratuons (see https://github.com/pact-foundation/pact-js/issues/299#issuecomment-492627721 for background).

Unless there is something we're missing?

**Comment by vgrigoruk** [comment]
did see that one, @mefellows. Looks like this ticket needs to be closed then.
It is just a bit annoying to pull @types/* in JS project, where we don't need them.

**Comment by TimothyJones** [comment]
I agree. This isn’t pact-ts (even if it is largely written in typescript).

Should the types be extracted to a PR to @types?

**Comment by mefellows** [comment]
Good idea @TimothyJones. I agree, although we're talking about a minor cost (and probably zero inconvenience) it's not ideal having the types exposed.

@vgrigoruk would you be willing to look into that? I've not done it before, but presumably it isn't super difficult.

**Comment by YOU54F** [comment]
what is the issue with the additional types files being pulled in? the additional space required should be minimal, and unless you are requiring pact-js as a dependency in your production packages, it would get bundled with your project if you build with webpack or similar.

I think because express is imported into the type definition file for the verifier, it will cause typescript users to break, and may cause issues for users with yarn/pnpm package managers.

I wonder if a better place for them is devDeps and peerDeps and a user can choose to install, if they wish.

https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies
https://github.com/LionC/express-basic-auth/issues/4

I don't transpile my verifier code into javascript, because it's not production code, and it run it with ts-node, so it uses the verifier.d.ts typing file supplied with the compiled pact-js, and therefore requires @types/express.

There seems to be no definitive answer on whether the consumers of a package, should pull in the @types if they need them (the error is pretty informative) and I have no issue in pulling them in my project, rather than the types being shipped for all.

also to note, even if these 3rd party types aren't included, every consumer of pact-js will pull in type definitions when pulling down the pact js module from npm, as the tsconfig has `declartion:true` which is good for me, and we write our pact tests in typescript, but unneccessary potentially for plain js users.

For now, I am happy with them being moved to devDeps, pulling in `@types/express` into my work and home projects, and we can see if this had a wider impact on other ts consumers of pact-js.

I wish there appeared to be official guidance from microsoft/definittlyTyped with regards to this, but I am yet to find it!

**Comment by YOU54F** [comment]
submitting a PR to defTyped - https://github.com/DefinitelyTyped/DefinitelyTyped  seems a sensible suggestion from @TimothyJones but I am not sure how easy it is to keep it up to date, when you make changes to your interfaces, where are shipping it directly with your codebase means that it's always in sync.

**Comment by TimothyJones** [comment]
Hm, that’s a good point about release cycle. Perhaps there’s a case for @pact-foundation/types?

I don’t actually use typescript myself, so I’m not super familiar with the ecosystem. 

I don’t think it’s high priority, but it seems like this dependency on another library’s types shouldn’t be something we depend on in a (published as) JS project- especially if it’s causing issues for people.

Providing types for Pact-js definitely provides value for users, I just don’t think it should be the responsibility of a repository published in JS.

How do other big JS projects provide their types?

**Comment by mefellows** [comment]
These are all really good points (and very much thanks!), but I'm wondering if a PR is now the place to manage this. Carry on for now, as I can't move it to an issue. I can see both sides and would like to get to a nice resolution - some weekend reading for me coming up!

**Pull request closed without merging**
